SELECT * FROM DICTIONARY;

SELECT * FROM USER_TABLES;
SELECT * FROM ALL_TABLES;
SELECT * FROM USER_USERS;
SELECT * FROM DBA_USERS;

SELECT * FROM DBA_OBJECTS;
SELECT * FROM DBA_TABLES WHERE OWNER='RAPHALEN';
SELECT * FROM DBA_INDEXES WHERE OWNER='RAPHALEN';

SELECT * FROM V$INSTANCE;
SELECT * FROM V$PARAMETER;

SELECT * FROM V$DBFILE;
SELECT * FROM V$DATAFILE;
SELECT * FROM DBA_DATA_FILES;

SELECT * FROM V$LOGFILE;
SELECT * FROM V$LOG;
SELECT * FROM V$LOG_HISTORY;

SELECT * FROM V$CONTROLFILE;
SELECT * FROM V$DATABASE;