/* Generated By:JavaCC: Do not edit this line. CalcConstants.java */
package calc;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface CalcConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int READ = 6;
  /** RegularExpression Id. */
  int WRITE = 7;
  /** RegularExpression Id. */
  int CONSTANT = 8;
  /** RegularExpression Id. */
  int DIGIT = 9;
  /** RegularExpression Id. */
  int IDENTIFIER = 10;
  /** RegularExpression Id. */
  int LETTER = 11;
  /** RegularExpression Id. */
  int LPAREN = 12;
  /** RegularExpression Id. */
  int RPAREN = 13;
  /** RegularExpression Id. */
  int ADD = 14;
  /** RegularExpression Id. */
  int SUB = 15;
  /** RegularExpression Id. */
  int MUL = 16;
  /** RegularExpression Id. */
  int DIV = 17;
  /** RegularExpression Id. */
  int AFF = 18;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "\"read\"",
    "\"write\"",
    "<CONSTANT>",
    "<DIGIT>",
    "<IDENTIFIER>",
    "<LETTER>",
    "\"(\"",
    "\")\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\":=\"",
  };

}
